workdir: '/home/debian/cami2_rhizosphere'

threads: 28

rhizosphere_linkfile: 'data/rhizosphere.linkfile'

refseq_url: 'https://openstack.cebitec.uni-bielefeld.de:8080/swift/v1/CAMI_2_DATABASES/RefSeq_genomic_20190108.tar'

cami_client_url: 'https://data.cami-challenge.org/camiClient.jar'

samples:
    sample_0: 'data/rhizosphere/reads/rhimgCAMI2_short_read_sample_0_reads.fq.gz'
    sample_1: 'data/rhizosphere/reads/rhimgCAMI2_short_read_sample_1_reads.fq.gz'
